spring:
  config:
    import: application-secret.yml
  security:
    oauth2:
      client:
        registration:
          google:
            clientName: Google
            clientId: 955078356844-tdscr8bblqhqncg9lpf8d572gvcnqsrq.apps.googleusercontent.com
            clientAuthenticationMethod: client_secret_basic
            authorizationGrantType: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
          kakao:
            clientName: Kakao
            clientId: 043b49ec68928d5d4ea92a937d1f05c5
            clientAuthenticationMethod: POST
            authorizationGrantType: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
          naver:
            clientName: Naver
            clientId: 7im4pcNAxsjLpc3fJ2TT
            clientAuthenticationMethod: POST
            authorizationGrantType: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope:
              - email
        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response

server:
  port: 8080
  serverAddress: localhost

mybatis:
  mapper-locations:
    - /mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

