name: Deploy to EC2 (Docker Compose)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show workspace (debug)
        run: |
          pwd
          ls -la

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        working-directory: .
        run: mvn -U -B clean package -DskipTests

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: target/tripsketch_back-0.0.1-SNAPSHOT.jar
          target: ${{ secrets.EC2_PATH }}/app/
          overwrite: true

      - name: Restart Docker Compose on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            cd ${{ secrets.EC2_PATH }}
            mv -f app/tripsketch_back-0.0.1-SNAPSHOT.jar app/tripsketch.jar
            docker compose up -d --build
            docker compose ps
